twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        ga_tracking: '%env(GOOGLE_ANALYTICS)%'
        google_recaptcha_site: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'